// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapifirst.Models;

#nullable disable

namespace webapifirst.Migrations
{
    [DbContext(typeof(FoodDeliveryContext))]
    [Migration("20250916082954_addTblRefreshtoken")]
    partial class addTblRefreshtoken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapifirst.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("webapifirst.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("webapifirst.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("webapifirst.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("dateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateEdit")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("dlt")
                        .HasColumnType("tinyint");

                    b.Property<string>("opAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("webapifirst.Models.RefreshToken", b =>
                {
                    b.Property<string>("RefreshTokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsRevoke")
                        .HasColumnType("tinyint");

                    b.Property<string>("RefreshTokenSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("webapifirst.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("dateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateEdit")
                        .HasColumnType("datetime2");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.Property<string>("opAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Role for admin",
                            Name = "Admin",
                            dlt = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Role for user",
                            Name = "User",
                            dlt = (byte)0
                        });
                });

            modelBuilder.Entity("webapifirst.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("dateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateEdit")
                        .HasColumnType("datetime2");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.Property<string>("opAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "IX_unique_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapifirst.Models.UserRole", b =>
                {
                    b.Property<string>("UserRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("dateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateEdit")
                        .HasColumnType("datetime2");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.Property<string>("opAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("webapifirst.Models.OrderDetail", b =>
                {
                    b.HasOne("webapifirst.Models.Order", "order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapifirst.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("webapifirst.Models.Product", b =>
                {
                    b.HasOne("webapifirst.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webapifirst.Models.UserRole", b =>
                {
                    b.HasOne("webapifirst.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapifirst.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapifirst.Models.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("webapifirst.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("webapifirst.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("webapifirst.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
