// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapifirst.Models;

#nullable disable

namespace webapifirst.Migrations
{
    [DbContext(typeof(FoodDeliveryContext))]
    partial class FoodDeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapifirst.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("webapifirst.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("webapifirst.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<byte>("dlt")
                        .HasColumnType("tinyint");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("webapifirst.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("dateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateEdit")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("dlt")
                        .HasColumnType("tinyint");

                    b.Property<string>("opAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcEdit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("webapifirst.Models.OrderDetail", b =>
                {
                    b.HasOne("webapifirst.Models.Order", "order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapifirst.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("webapifirst.Models.Product", b =>
                {
                    b.HasOne("webapifirst.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webapifirst.Models.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("webapifirst.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
